name: Build backend

on: workflow_dispatch

    
jobs:
  build:
    runs-on: ubuntu-20.04

    
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:       
        - uses: actions/checkout@v2

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}


        - name: build backend
          working-directory: backend
          run: |
            npm install
            npm run test
            npm run build
