name: Decir hola en la consola

on: workflow_dispatch

    
jobs:
  build:
    runs-on: ubuntu-20.04

    
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
      - name: Escribir en consola
        run: |
          ll
     
      - name: build backend
        working-directory: backend
        run: |
         npm install
         npm run test
         npm run build
            
      -  name: Escribir en consola fin
         run: |
          echo 'Termino la action'
